#!/usr/bin/env bash

spaces (){
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
	CHINESE_NUMBERS=$(echo "{ \"1\": \"一\", \"2\": \"二\", \"3\": \"三\", \"4\": \"四\", \"5\": \"五\", \"6\": \"六\", \"7\": \"七\", \"8\": \"八\", \"9\": \"九\", \"10\": \"十\" }" | jq)
	seq 1 9 | jq --argjson windows "${WORKSPACE_WINDOWS}" --argjson chinese "${CHINESE_NUMBERS}" --slurp -Mc 'map(tostring) | map({id: $chinese[.], windows: ($windows[.]//0)})'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
